### ISSUE TITLE
error on windows

### ISSUE THREAD

**Issue by S0URON** [Domino007/google_job_scraper#1]
after cloning and installing dependecies i ran the script as shown in the readme, 
the script starts installs, chrome driver, launches the chrome window and when it gets to careers.google.com it throws this error;
```
====== WebDriver manager ======
## ====== WebDriver manager ======
Current google-chrome version is 98.0.4758
## Current google-chrome version is 98.0.4758
Get LATEST chromedriver version for 98.0.4758 google-chrome
## Get LATEST chromedriver version for 98.0.4758 google-chrome
Driver [C:\Users\mokni\.wdm\drivers\chromedriver\win32\98.0.4758.80\chromedriver.exe] found in cache
## Driver [C:\Users\mokni\.wdm\drivers\chromedriver\win32\98.0.4758.80\chromedriver.exe] found in cache

DevTools listening on ws://127.0.0.1:56767/devtools/browser/ad4c5618-e193-44e1-b74d-dbc14bc7ec1c
.\keywords.txt found...
Working on keyword - frontend developer canada
[14572:4540:0210/104259.652:ERROR:chrome_browser_main_extra_parts_metrics.cc(227)] START: ReportBluetoothAvailability(). If you don't see the END: message, this is crbug.com/1216328.
[14572:4540:0210/104259.652:ERROR:chrome_browser_main_extra_parts_metrics.cc(230)] END: ReportBluetoothAvailability()
[14572:4540:0210/104259.653:ERROR:chrome_browser_main_extra_parts_metrics.cc(235)] START: GetDefaultBrowser(). If you don't see the END: message, this is crbug.com/1216328.
[14572:9956:0210/104259.654:ERROR:device_event_log_impl.cc(214)] [10:42:59.653] USB: usb_device_handle_win.cc:1049 Failed to read descriptor from node connection: A device attached to the system is not functioning. (0x1F)
[14572:4540:0210/104259.661:ERROR:chrome_browser_main_extra_parts_metrics.cc(239)] END: GetDefaultBrowser()
Traceback (most recent call last):
  File "C:\Users\...\Documents\google_job_scraper\jobber.py", line 45, in <module>
    google_handler.keyword_jobsearch(keyword)
  File "C:\Users\...\Documents\google_job_scraper\google_handler\google_page_handler.py", line 90, in keyword_jobsearch
    self.clear_search_input_element(self.driver, GoogleJobsPageLocators)
  File "C:\Users\...\Documents\google_job_scraper\google_handler\util.py", line 32, in clear_search_input_element
    self.click_helper(driver, locator_class.clear_search_button)
  File "C:\Users\...\Documents\google_job_scraper\google_handler\util.py", line 24, in click_helper
    element = driver.find_element(By.CSS_SELECTOR, selector)
  File "C:\Users\...\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\selenium\webdriver\remote\webdriver.py", line 1244, in find_element
    return self.execute(Command.FIND_ELEMENT, {
  File "C:\Users\...\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\selenium\webdriver\remote\webdriver.py", line 424, in execute
    self.error_handler.check_response(response)
  File "C:\Users\...\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\selenium\webdriver\remote\errorhandler.py", line 247, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.NoSuchElementException: Message: no such element: Unable to locate element: {"method":"css selector","selector":"button.gb_jf"}
  (Session info: chrome=98.0.4758.82)
Stacktrace:
Backtrace:
        Ordinal0 [0x00C27AC3+2587331]
        Ordinal0 [0x00BBADD1+2141649]
        Ordinal0 [0x00AB3BB8+1063864]
        Ordinal0 [0x00AE01CE+1245646]
        Ordinal0 [0x00AE03CB+1246155]
        Ordinal0 [0x00B0A612+1418770]
        Ordinal0 [0x00AF86D4+1345236]
        Ordinal0 [0x00B08A0A+1411594]
        Ordinal0 [0x00AF84A6+1344678]
        Ordinal0 [0x00AD53F6+1201142]
        Ordinal0 [0x00AD62E6+1204966]
        GetHandleVerifier [0x00DCDF22+1680738]
        GetHandleVerifier [0x00E80DBC+2413564]
        GetHandleVerifier [0x00CBD151+563089]
        GetHandleVerifier [0x00CBBF13+558419]
        Ordinal0 [0x00BC081E+2164766]
        Ordinal0 [0x00BC5508+2184456]
        Ordinal0 [0x00BC5650+2184784]
        Ordinal0 [0x00BCF5BC+2225596]
        BaseThreadInitThunk [0x76306739+25]
        RtlGetFullPathName_UEx [0x77758AFF+1215]
        RtlGetFullPathName_UEx [0x77758ACD+1165]
```

**Comment by AxtinM** [comment]
solved the issue
